// SPDX-License-Identifier: Apache-2.0
#pragma once

#include "driver/gpio.h"
#include "driver/i2c_types.h"
#include "driver/uart.h"

#define HUMIDIFIER_I2C_PORT I2C_NUM_0
#define HUMIDIFIER_I2C_SDA_GPIO GPIO_NUM_21
#define HUMIDIFIER_I2C_SCL_GPIO GPIO_NUM_22
#define HUMIDIFIER_I2C_FREQ_HZ 100000U
#define HUMIDIFIER_RELAY_ADDRESS 0x38U

#define HUMIDIFIER_RELAY_PUMP 0U
#define HUMIDIFIER_RELAY_FLOW 1U
#define HUMIDIFIER_RELAY_ION 2U
#define HUMIDIFIER_RELAY_TURBO3 3U
#define HUMIDIFIER_RELAY_TURBO2 4U
#define HUMIDIFIER_RELAY_TURBO1 5U

#define HUMIDIFIER_WATER_LED_GPIO GPIO_NUM_25

#define HUMIDIFIER_PMS_UART UART_NUM_1
#define HUMIDIFIER_PMS_TX_GPIO GPIO_NUM_17
#define HUMIDIFIER_PMS_RX_GPIO GPIO_NUM_16
#define HUMIDIFIER_PMS_BAUDRATE 9600
#define HUMIDIFIER_PMS_WAKE_WARMUP_MS 30000U

_Static_assert(HUMIDIFIER_RELAY_PUMP != HUMIDIFIER_RELAY_FLOW, "relay channels must be unique");
_Static_assert(HUMIDIFIER_RELAY_TURBO1 != HUMIDIFIER_RELAY_TURBO2, "fan relays must be unique");
_Static_assert(HUMIDIFIER_RELAY_TURBO2 != HUMIDIFIER_RELAY_TURBO3, "fan relays must be unique");
